/* ============================================================
   src/ui.js — Vite-native ES module for pure-JS UI utilities.
   No JSX, no React. Importable in both browser and Node.js.

   React components (Card, Metric, Pill, Table, Alert, ModuleIntro,
   InsightGrid, InsightCard, Segmented, Spark) live in src/ui.jsx,
   which re-exports everything here and adds the JSX components.

   public/legacy/ui.jsx is the unchanged browser-Babel shim that
   assigns every symbol to window.* for legacy script consumers
   (charts.jsx, sidebar.jsx, views-*.jsx, app.jsx).

   Migration phase: 6c (adapter-based first step for UI layer).
   ============================================================ */

// ---- formatters ----
export const fmtPct = (v, d = 1) => (v >= 0 ? "" : "−") + Math.abs(v * 100).toFixed(d) + "%";
export const fmtPctSigned = (v, d = 1) => (v >= 0 ? "+" : "−") + Math.abs(v * 100).toFixed(d) + "%";
export const fmtUSD = v => "$" + Math.round(v).toLocaleString("en-US");
export const fmtUSDc = v => "$" + v.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
export const fmtUSDSigned = v => (v >= 0 ? "+" : "−") + "$" + Math.round(Math.abs(v)).toLocaleString("en-US");
export const fmtNum = (v, d = 2) => v.toFixed(d);

// stable color per asset index
export const SERIES_COLORS = [
  "var(--accent)", "var(--accent-2)",
  "oklch(0.72 0.13 295)", "oklch(0.78 0.13 95)",
  "oklch(0.70 0.13 25)",  "oklch(0.74 0.12 145)",
  "oklch(0.70 0.12 330)", "oklch(0.76 0.11 60)",
];
export function assetColor(i) { return SERIES_COLORS[i % SERIES_COLORS.length]; }

export const I18N = {
  en: {
    language: "Language",
    toggleTheme: "Toggle theme",
    holdings: "holdings",
    range: "range",
    annReturn: "Ann. Return",
    sharpe: "Sharpe",
    maxDd: "Max DD",
    realPrices: "Real Prices",
    loadingPrices: "Loading Prices",
    partialPrices: "Partial Prices",
    mockPrices: "Mock Prices",
    addInstrument: "Add instrument",
    searchTicker: "Search ticker or name...",
    added: "added",
    noMatch: "No match for",
    portfolio: "Portfolio",
    position: "position",
    positions: "positions",
    emptyHoldings: "Search above to add your first instrument.",
    remove: "Remove",
    lotsTitle: "Position lots (shares)",
    lotsHelp: "Weights are computed from lots x latest price.",
    portfolioValue: "Portfolio value",
    dataRange: "Data range",
    from: "From",
    to: "To",
    analysisProfile: "Analysis profile",
    advancedAssumptions: "Advanced assumptions",
    riskFreeRate: "Risk-free rate",
    rfHelp: "Used in Sharpe & Sortino. Defaults to 3-month T-bill.",
    mcHorizon: "MC horizon",
    mcHorizonHelp: "Projection length for Monte Carlo simulation.",
    mcPaths: "MC paths",
    mcPathsHelp: "More paths = smoother distribution, slower compute.",
    dataAdapterReady: "Data adapter ready",
    proxyChecking: "Proxy checking",
    proxyReady: "Proxy ready",
    proxyKeyMissing: "Proxy online - key missing",
    proxyOffline: "Proxy offline",
    realPricesCount: "Real prices",
    partialPricesCount: "Partial prices",
    loadingHistory: "Loading price history",
    mockPricesLower: "Mock prices",
    quoteProfile: "Quote/profile",
    loadingQuoteProfile: "Loading quote/profile",
    mockCompanyData: "Mock company data",
    noHoldingsYet: "No holdings yet",
    emptyStateHelp: "Use the search in the control panel to add stock or ETF tickers, then enter position lots to build your portfolio.",
    rateLimitWarn: "Rate limit reached — some data may be delayed.",
    savedPortfolios: "Saved portfolios",
    portfolioNamePlaceholder: "Portfolio name…",
    savePortfolio: "Save",
    overwritePortfolio: "Overwrite",
    loadPortfolio: "Load",
    deletePortfolio: "Delete",
    resetToDefault: "Reset to default",
    saveErrorEmpty: "Name is required",
    saveErrorMax: "Maximum 10 portfolios saved",
    saveErrorStorage: "Could not save — storage full",
    csvImportExport: "CSV import / export",
    csvImport: "Import CSV",
    csvExport: "Export CSV",
    csvImportHelp: "Format: ticker,lots (header optional)",
    csvImportedRows: "holdings imported",
    csvSkippedRows: "rows skipped",
    csvNoValidRows: "No valid rows found",
    csvReadError: "Could not read file",
    csvUnsupported: "Unsupported:",
    printReport: "Print Report",
    printHeaderTitle: "Portfolio Analytics Report",
    printHeaderGenerated: "Generated",
    printHeaderRange: "Date range",
    printHeaderBenchmark: "Benchmark",
    printHeaderSource: "Data source",
    printHeaderNote: "Notes",
    printHeaderDisclaimer: "For analytical purposes only — not financial advice. Past performance does not guarantee future results.",
    customDateRange: "Custom date range",
    dateRangeMissing: "Start and end date required",
    dateRangeStartAfterEnd: "Start must be before end",
    dateRangeFutureEnd: "End date cannot be in the future",
    dateRangeTooShort: "Range must be at least 30 days",
    extendedUniverse: "Extended universe",
    extendedUniverseNote: "Mock data is synthetic until real history loads",
    addExtended: "Add as extended ticker",
    portfolioNotes: "Portfolio notes",
    portfolioNotesPlaceholder: "Investment thesis, last review, reminders…",
    portfolioNotesChars: "chars",
    lotsShares: "Shares",
    lotsPrice: "Price",
    lotsValue: "Value",
    averageCost: "Avg. Cost",
    firstBought: "First Bought",
    unrealizedPnl: "Unrealized P&L",
    unrealizedReturn: "Unrealized Return",
    costBasis: "Cost Basis",
    missingCostBasis: "Missing cost basis",
    jsonBackup: "JSON backup",
    jsonBackupHelp: "Export full state including cost basis. Import to restore on any device.",
    jsonExport: "Export JSON",
    jsonImport: "Import JSON",
    jsonImportedOk: "Portfolio restored",
    jsonErrorVersion: "Unsupported backup version",
    jsonErrorNoHoldings: "No valid holdings in backup",
    jsonErrorInvalid: "Invalid backup file",
    snapshotHistory: "Portfolio value history",
    snapshotHistoryHelp: "Recorded only from live-price sessions",
    snapshotWow: "Week",
    snapshotMom: "Month",
    snapshotYtd: "YTD",
    snapshotInception: "Since first session",
    snapshotNoHistory: "Not enough history yet",
    snapshotVs: "vs",
    saveActiveState: "Save Current State",
    activeStateSaved: "Current state saved",
    activeStateLastSaved: "Last saved:",
    activeStateNeverSaved: "Not saved yet",
    openSidebar: "Open sidebar",
    closeSidebar: "Close sidebar",
  },
  tr: {
    language: "Dil",
    toggleTheme: "Temayı değiştir",
    holdings: "varlık",
    range: "aralık",
    annReturn: "Yıllık Getiri",
    sharpe: "Sharpe",
    maxDd: "Maks. Düşüş",
    realPrices: "Canlı Fiyat",
    loadingPrices: "Fiyat Yükleniyor",
    partialPrices: "Kısmi Fiyat",
    mockPrices: "Model Fiyat",
    addInstrument: "Varlık ekle",
    searchTicker: "Sembol veya şirket ara...",
    added: "eklendi",
    noMatch: "Eşleşme yok:",
    portfolio: "Portföy",
    position: "pozisyon",
    positions: "pozisyon",
    emptyHoldings: "İlk varlığı eklemek için yukarıdaki aramayı kullan.",
    remove: "Sil",
    lotsTitle: "Pozisyon lotları",
    lotsHelp: "Ağırlıklar lot x son fiyat üzerinden hesaplanır.",
    portfolioValue: "Portföy değeri",
    dataRange: "Veri aralığı",
    from: "Başlangıç",
    to: "Bitiş",
    analysisProfile: "Profil analizi",
    advancedAssumptions: "Gelişmiş varsayımlar",
    riskFreeRate: "Risksiz faiz",
    rfHelp: "Sharpe ve Sortino hesaplarında kullanılır. Varsayılan olarak 3 aylık T-Bill kabul edilir.",
    mcHorizon: "MC vadesi",
    mcHorizonHelp: "Monte Carlo simülasyonu için projeksiyon süresi.",
    mcPaths: "MC yol sayısı",
    mcPathsHelp: "Daha fazla yol daha pürüzsüz dağılım üretir, hesaplama süresini artırır.",
    dataAdapterReady: "Veri adaptörü hazır",
    proxyChecking: "Proxy kontrol ediliyor",
    proxyReady: "Proxy hazır",
    proxyKeyMissing: "Proxy çevrimiçi - key eksik",
    proxyOffline: "Proxy çevrimdışı",
    realPricesCount: "Canlı fiyat",
    partialPricesCount: "Kısmi fiyat",
    loadingHistory: "Fiyat geçmişi yükleniyor",
    mockPricesLower: "Model fiyat",
    quoteProfile: "Quote/profil",
    loadingQuoteProfile: "Quote/profil yükleniyor",
    mockCompanyData: "Model şirket verisi",
    noHoldingsYet: "Henüz varlık yok",
    emptyStateHelp: "Portföy oluşturmak için kontrol panelindeki aramadan hisse veya ETF sembolü ekle, ardından pozisyon lotlarını gir.",
    rateLimitWarn: "Rate limit sınırına ulaşıldı — bazı veriler gecikebilir.",
    savedPortfolios: "Kaydedilen portföyler",
    portfolioNamePlaceholder: "Portföy adı…",
    savePortfolio: "Kaydet",
    overwritePortfolio: "Üzerine yaz",
    loadPortfolio: "Yükle",
    deletePortfolio: "Sil",
    resetToDefault: "Varsayılana sıfırla",
    saveErrorEmpty: "Ad gerekli",
    saveErrorMax: "En fazla 10 portföy kaydedilebilir",
    saveErrorStorage: "Kaydedilemedi — depolama dolu",
    csvImportExport: "CSV içe/dışa aktarım",
    csvImport: "CSV İçe Aktar",
    csvExport: "CSV Dışa Aktar",
    csvImportHelp: "Format: sembol,lot (başlık isteğe bağlı)",
    csvImportedRows: "varlık içe aktarıldı",
    csvSkippedRows: "satır atlandı",
    csvNoValidRows: "Geçerli satır bulunamadı",
    csvReadError: "Dosya okunamadı",
    csvUnsupported: "Desteklenmiyor:",
    printReport: "Raporu Yazdır",
    printHeaderTitle: "Portföy Analitik Raporu",
    printHeaderGenerated: "Oluşturulma tarihi",
    printHeaderRange: "Tarih aralığı",
    printHeaderBenchmark: "Kıyaslama",
    printHeaderSource: "Veri kaynağı",
    printHeaderNote: "Notlar",
    printHeaderDisclaimer: "Yalnızca analitik amaçlıdır — yatırım tavsiyesi değildir. Geçmiş performans gelecekteki sonuçları garanti etmez.",
    customDateRange: "Özel tarih aralığı",
    dateRangeMissing: "Başlangıç ve bitiş tarihi gerekli",
    dateRangeStartAfterEnd: "Başlangıç bitiş tarihinden önce olmalı",
    dateRangeFutureEnd: "Bitiş tarihi gelecekte olamaz",
    dateRangeTooShort: "Aralık en az 30 gün olmalı",
    extendedUniverse: "Genişletilmiş evren",
    extendedUniverseNote: "Gerçek geçmiş yüklenene kadar model veri kullanılır",
    addExtended: "Genişletilmiş sembol ekle",
    portfolioNotes: "Portföy notları",
    portfolioNotesPlaceholder: "Yatırım tezi, son inceleme, notlar…",
    portfolioNotesChars: "karakter",
    lotsShares: "Hisse",
    lotsPrice: "Fiyat",
    lotsValue: "Değer",
    averageCost: "Ort. Maliyet",
    firstBought: "İlk Alım",
    unrealizedPnl: "Gerçekleşmemiş K/Z",
    unrealizedReturn: "Gerçekleşmemiş Getiri",
    costBasis: "Maliyet",
    missingCostBasis: "Maliyet eksik",
    jsonBackup: "JSON yedek",
    jsonBackupHelp: "Maliyet bazı dahil tam portföy durumunu dışa aktar. Herhangi bir cihazda geri yüklemek için içe aktar.",
    jsonExport: "JSON Dışa Aktar",
    jsonImport: "JSON İçe Aktar",
    jsonImportedOk: "Portföy geri yüklendi",
    jsonErrorVersion: "Desteklenmeyen yedek sürümü",
    jsonErrorNoHoldings: "Yedekte geçerli varlık yok",
    jsonErrorInvalid: "Geçersiz yedek dosyası",
    snapshotHistory: "Portföy değer geçmişi",
    snapshotHistoryHelp: "Yalnızca canlı fiyat oturumlarından kaydedilir",
    snapshotWow: "Hafta",
    snapshotMom: "Ay",
    snapshotYtd: "YTD",
    snapshotInception: "İlk oturumdan beri",
    snapshotNoHistory: "Henüz yeterli geçmiş yok",
    snapshotVs: "karşılaştırma",
    saveActiveState: "Geçerli Durumu Kaydet",
    activeStateSaved: "Geçerli durum kaydedildi",
    activeStateLastSaved: "Son kayıt:",
    activeStateNeverSaved: "Henüz kaydedilmedi",
    openSidebar: "Kenar çubuğunu aç",
    closeSidebar: "Kenar çubuğunu kapat",
  },
};

export function t(lang, key) {
  return (I18N[lang] && I18N[lang][key]) || I18N.en[key] || key;
}
